version: '3.9'

services:
  postgres_db:   # PostgreSQL database servicename
    image: postgres:16    # Official PostgreSQL image downloaded from Docker Hub
    container_name: banking-postgres     # Custom container name
    environment:    # Database credentials
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:    # Port mapping HOST_PORT : CONTAINER_PORT
      - "5432:5432"

    # Persistent storage for PostgreSQL data
    # Without this volume, all database data will be lost if the container is removed
    volumes:    
      - postgres_data:/var/lib/postgresql/data

volumes:    # Named Docker volumes to persist data outside of the container lifecycle
  postgres_data: